### ISSUE TITLE
_node command line param ordering can cause failure

### ISSUE THREAD

**Issue by spollack** [Sage/streamlinejs#192]
this works fine:
_node -m -c config._js

reversing the parameter order causes it to fail:
_node -c -m config._js
ENOENT, stat '/Users/spollack/workspace/rivaliq-server/-m'
Error: ENOENT, stat '/Users/spollack/workspace/rivaliq-server/-m'
    <<< async stack >>>

    at _compile (/usr/local/lib/node_modules/streamline/lib/callbacks/compile.js:266:13)
    at __1 (/usr/local/lib/node_modules/streamline/lib/callbacks/compile.js:306:2)
    at value__1 (/usr/local/lib/node_modules/streamline/lib/callbacks/builtins.js:131:28)
    at exports_compile__3 (/usr/local/lib/node_modules/streamline/lib/callbacks/compile.js:305:1)
    <<< raw stack >>>Error: ENOENT, stat '/Users/spollack/workspace/rivaliq-server/-m'

**Comment by bjouhier** [comment]
Fixed in 1.0. CLI is now parsed with commander.
