### ISSUE TITLE
"break target not set" when breaking out of loop within catch

### ISSUE THREAD

**Issue by psung** [Sage/streamlinejs#264]
Here's a minimal test case that reproduces the issue I'm seeing:

```javascript
function foo(_) {}

try {

} catch (err) {
  while (true) {
    if (foo(_)) {
      break;
    }
  }
}
```

When executing the file above with streamline 0.12.0, the compiler complains with the following:

```
$ _node test._js
/myproj/node_modules/streamline/lib/callbacks/transform.js:1960
                        throw new Error(message);
                              ^
Error: error streamlining /myproj/test._js: internal error: break target not set
STACK:
Error: internal error: break target not set
    at _doIt (/myproj/node_modules/streamline/lib/callbacks/transform.js:1206:24)
    at _propagate (/myproj/node_modules/streamline/lib/callbacks/transform.js:186:20)
    at _doIt (/myproj/node_modules/streamline/lib/callbacks/transform.js:1215:11)
    at _propagate (/myproj/node_modules/streamline/lib/callbacks/transform.js:196:58)
    at _doIt (/myproj/node_modules/streamline/lib/callbacks/transform.js:1215:11)
    at _propagate (/myproj/node_modules/streamline/lib/callbacks/transform.js:186:20)
    at _doIt (/myproj/node_modules/streamline/lib/callbacks/transform.js:1215:11)
    at _propagate (/myproj/node_modules/streamline/lib/callbacks/transform.js:196:58)
    at _doIt (/myproj/node_modules/streamline/lib/callbacks/transform.js:1069:81)
    at _propagate (/myproj/node_modules/streamline/lib/callbacks/transform.js:186:20)

    at exports.transform (/myproj/node_modules/streamline/lib/callbacks/transform.js:1960:10)
    at Object.streamliners._js [as ._js] (/myproj/node_modules/streamline/lib/compiler/underscored.js:108:5)
    at Object.run (/myproj/node_modules/streamline/lib/compiler/underscored.js:213:25)
    at Object.exports.register (/myproj/node_modules/streamline/lib/compiler/register.js:93:14)
    at Object.exports.run (/myproj/node_modules/streamline/lib/compiler/command.js:123:26)
    at Object.<anonymous> (/myproj/node_modules/streamline/bin/_node:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Let me know if any more info from me would be helpful. Thanks!

**Comment by bjouhier** [comment]
@psung Should be fixed too in 0.12.1 too.

**Comment by psung** [comment]
Thanks for the quick fix!

**Comment by bjouhier** [comment]
Please let me know if you hit other regressions. The narcissus -> esprima change was a big change and I would like to get back to a very stable state as quickly as possible.
