### ISSUE TITLE
"Cannot read property 'type' of undefined" with certain try..catch..finally constructs

### ISSUE THREAD

**Issue by psung** [Sage/streamlinejs#265]
Here's a minimal test case that reproduces the issue I'm seeing:

```javascript
try {
} catch (error) {
  var value = {$weirdkey: null};
  setTimeout(_, 1000);
} finally {
}
```

When executing the file above with streamline 0.12.0, the compiler complains of the following:

```
$ _node test._js 

/myproj/node_modules/streamline/lib/callbacks/transform.js:1960
                        throw new Error(message);
                              ^
Error: error streamlining /myproj/test._js: Cannot read property 'type' of undefined
STACK:
TypeError: Cannot read property 'type' of undefined
    at CodeGenerator.generateExpression (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2401:20)
    at CodeGenerator.generatePropertyKey (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:990:26)
    at CodeGenerator.Expression.Property (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2124:22)
    at CodeGenerator.generateExpression (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2407:28)
    at /myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2139:33
    at withIndent (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:582:9)
    at CodeGenerator.Expression.ObjectExpression (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2138:13)
    at CodeGenerator.generateExpression (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:2407:28)
    at CodeGenerator.generateAssignment (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:1007:22)
    at CodeGenerator.Expression.AssignmentExpression (/myproj/node_modules/streamline/node_modules/escodegen/escodegen.js:1788:25)

    at exports.transform (/myproj/node_modules/streamline/lib/callbacks/transform.js:1960:10)
    at Object.streamliners._js [as ._js] (/myproj/node_modules/streamline/lib/compiler/underscored.js:108:5)
    at Object.run (/myproj/node_modules/streamline/lib/compiler/underscored.js:213:25)
    at Object.exports.register (/myproj/node_modules/streamline/lib/compiler/register.js:93:14)
    at Object.exports.run (/myproj/node_modules/streamline/lib/compiler/command.js:123:26)
    at Object.<anonymous> (/myproj/node_modules/streamline/bin/_node:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Let me know if I can provide any additional info.

I've tried to minimize the test case above; in particular, the file runs successfully if any of the following are changed:

* The key `$weirdkey` is changed to `normalkey`
* The underscored call to `setTimeout` is removed or changed to a normal, non-underscored function call
* The `finally` is removed from the `try..catch`

**Comment by bjouhier** [comment]
@psung. This is a regression between 0.10 and 0.12. I fixed it and published 0.12.1 to npm.
