### ISSUE TITLE
Mocha with fibers is broken

### ISSUE THREAD

**Issue by winniehell** [Sage/streamlinejs#273]
When I run [mocha](/mochajs/mocha) with `fibers` enabled, I get

```
TypeError: Object [...] has no method 'replace'
    at Module._compile (module.js:377:21)
    at Module.pModule._compile (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.streamliners._js [as ._js] (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/lib/compiler/underscored.js:118:12)
    at Object.run (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/lib/compiler/underscored.js:213:25)
    at Object.exports.register (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/lib/compiler/register.js:93:14)
    at Object.exports.run (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/lib/compiler/command.js:120:26)
    at Object.<anonymous> (/home/travis/build/winniehell/streamlinejs/node_modules/streamline/bin/_node:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I made a small example project [here](/winniehell/streamlinejs/tree/mocha-fibers-issue).

The issue seems to be introduced by 93c77c5ee9224faa3367c7f645176f895f47bd6f as part of #195. Please see also the corresponding [Travis CI builds](https://travis-ci.org/winniehell/streamlinejs/builds/61537020).

This issue might be related to #146.

**Comment by bjouhier** [comment]
Looks like `streamlined.code` is not a string at https://github.com/Sage/streamlinejs/blob/master/lib/compiler/underscored.js#L118

I don't have time to investigate now but it could be due to an incompatible version of source-map.

**Comment by winniehell** [comment]
Thank you for the hint! The problem seems to be in [lib/fibers/transform.js](/Sage/streamlinejs/blob/d0b55f8887379b219ba83c5912af7cee364fac83/lib/fibers/transform.js#L661). Replacing `return buffer;` (which is a `sourceMap.SourceNode` and not a string) by `return buffer.toString();` solves the issue for me.

**Comment by bjouhier** [comment]
I fixed it slightly differently so that the fix applies to all modes, not just fibers. Can you confirm that it works for you. Then I'll publish a 0.12.2.

**Comment by winniehell** [comment]
[Looks good](https://travis-ci.org/winniehell/streamlinejs/builds/61801141)! Great that you fixed the other modes, too. :+1: :shipit:
