### ISSUE TITLE
Can't access "this" when callback provides it

### ISSUE THREAD

**Issue by michael-ts** [Sage/streamlinejs#353]
I'm trying to streamline some code which uses node-sqlite3.  Per the [API][1], when I call the `run` function to INSERT a row, in the context of the callback the "this" variable will contain a property `lastID` containing the `last_insert_rowid()` i.e. it will tell me the rowid of the row I just inserted.

However, the `this` variable does not seem to get carried over into the next statement in the streamlined code:

```
var query = "INSERT INTO ..."
var x = db.run(query,_)
console.log(this)  // has no "lastID", only a couple function/wrappers

```
Similarly, if the query was an UPDATE or DELETE, `this.changes` is supposed to have the number of rows.

I tried a simple experiment to see if I could figure out how to get the lastID value, along the lines of this:

```
var query = "INSERT INTO ..."
var x = db.run(query,function(_) {
    return this.lastID
})
console.log(this)  // has no "lastID", only a couple function/wrappers

```

But this just made a horrible mess of error:

```
TypeError: invalid argument 0 to function ``: expected function, got string
    at typeError (/Users/michael/node/ix-server/node_modules/streamline-runtime/lib/util.js:37:12)
    at Object.argError (/Users/michael/node/ix-server/node_modules/streamline-runtime/lib/util.js:43:9)
/Users/michael/node/ix-server/node_modules/streamline-runtime/lib/util.js:39

```

Not sure if this is a bug, or if I'm just missing how I am to access the `this` variable properly.

  [1]: https://github.com/mapbox/node-sqlite3/wiki/API

**Comment by michael-ts** [comment]
As a workaround, the following _seems_ to work:

```
var query = "INSERT INTO ..."
var stmt = db.prepare(query)
stmt.run(_)
console.log(stmt.lastID)
```

I say _seems_ because in my test it works, but the `prepare` call has an optional callback to be called when the statement is prepared.  If I try to provide this callback I get an error, because I cannot simultaneously get the return value of the function, as well as the callback value.  (Is there some way to get both of these?)

**Comment by bjouhier** [comment]
I never encountered this API before. Streamline is designed to work with _standard_ node.js callbacks (`function(err, result) => void`). The value of `this` inside the callback and the value returned by the original API are not _directly_ accessible in streamline.

If `this` inside the callback refers to `stmt` your workaround will work.

You can  also access the value of `this` inside the callback with a wrapper:

```
// the wrapper
function run(db, query, cb) {
  db.run(query, function(err, result) { 
    cb(err, [this, result]); 
  });
}

// calling the wrapper (with destructuring to extract the returned values)
let [that, result] = run(db, query, _);
```

The wrapper technique can also help you with calls that also return a value (non standard). For example:
```
// wrapper
function prepare(db, sql, params, cb) {
  let stmt = db.prepare(sql, params, function(err) {
    cb(err, stmt);
  });
}

// calling it
let stmt = prepare(db, sql, params, _);
```
