### ISSUE TITLE
Error: Cannot find module 'streamline-runtime/lib/fibers/runtime'

### ISSUE THREAD

**Issue by michael-ts** [Sage/streamlinejs#354]
Running into an issue trying to use streamline under Ubuntu for Windows 10.

After installing streamline (I have tried both globally, and then either using "npm link" or setting my NODE_PATH, and locally) I am trying to invoke it as follows:

```
require("streamline").register({})
console.log("debug1")
require("./test2")
```

But this does not work, I get this error:

root@MEM:/mnt/c/Users/michael/Dropbox/node# node test.js
debug1
module.js:327
    throw err;
    ^

```
Error: Cannot find module 'streamline-runtime/lib/fibers/runtime'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/c/Users/michael/Dropbox/node/test2._js:3:51)
    at Module._compile (module.js:409:26)
    at Module._compile (/usr/lib/node_modules/streamline/lib/register.js:52:12)
    at Object.._js (/usr/lib/node_modules/streamline/lib/register.js:65:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

The exact same code was working earlier today on OS X as well, but I just tried to ssh in to my box and verify this, and now it is giving the exact same error.

**Comment by michael-ts** [comment]
I get similar errors no matter what runtime I specify.

**Comment by bjouhier** [comment]
You should install `streamline-runtime` (locally: `npm install --save streamline-runtime`).

If you deploy `*._js` files and rely on require hooks you must install both (`streamline` and `streamline-runtime`)

If you preprocess and deploy `*.js` files you only need `streamline-runtime` to run.

**Comment by michael-ts** [comment]
Ok, it seems to be working now.  I'm sure I had installed both, even though it seemed initially like installing `streamline` also installed `streamline-runtime`, but apparently something got in a bad state.  A fresh install of both modules before running and everything seems to be working again.
