### ISSUE TITLE
Error trying to register a loader interactively

### ISSUE THREAD

**Issue by michael-ts** [Sage/streamlinejs#355]
I create a new directory, cd to it, then run the following:

```
$ npm install streamline streamline-runtime

> fibers@1.0.15 install /Users/michael/nodetmp/tmp/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-48` exists; testing
Binary is fine; exiting
/Users/michael/nodetmp/tmp
`-- streamline@2.0.16
  +-- babel-core@6.24.0
  | +-- babel-code-frame@6.22.0
  | | +-- chalk@1.1.3
  | | | +-- ansi-styles@2.2.1
  | | | +-- escape-string-regexp@1.0.5
  | | | +-- has-ansi@2.0.0
  | | | | `-- ansi-regex@2.1.1
  | | | +-- strip-ansi@3.0.1
  | | | `-- supports-color@2.0.0
  | | +-- esutils@2.0.2
  | | `-- js-tokens@3.0.1
  | +-- babel-generator@6.24.0
  | | +-- detect-indent@4.0.0
  | | | `-- repeating@2.0.1
  | | |   `-- is-finite@1.0.2
  | | |     `-- number-is-nan@1.0.1
  | | +-- jsesc@1.3.0
  | | `-- trim-right@1.0.1
  | +-- babel-helpers@6.23.0
  | +-- babel-messages@6.23.0
  | +-- babel-register@6.24.0
  | | +-- core-js@2.4.1
  | | +-- home-or-tmp@2.0.0
  | | | +-- os-homedir@1.0.2
  | | | `-- os-tmpdir@1.0.2
  | | +-- mkdirp@0.5.1
  | | | `-- minimist@0.0.8
  | | `-- source-map-support@0.4.14
  | +-- babel-runtime@6.23.0
  | +-- babel-template@6.23.0
  | +-- babel-traverse@6.23.1
  | | +-- globals@9.16.0
  | | `-- invariant@2.2.2
  | |   `-- loose-envify@1.3.1
  | +-- babel-types@6.23.0
  | | `-- to-fast-properties@1.0.2
  | +-- babylon@6.16.1
  | +-- convert-source-map@1.4.0
  | +-- debug@2.6.3
  | | `-- ms@0.7.2
  | +-- json5@0.5.1
  | +-- lodash@4.17.4
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | +-- path-is-absolute@1.0.1
  | +-- private@0.1.7
  | +-- slash@1.0.0
  | `-- source-map@0.5.6
  +-- babel-plugin-streamline@2.0.26
  +-- babel-preset-es2015@6.24.0
  | +-- babel-plugin-check-es2015-constants@6.22.0
  | +-- babel-plugin-transform-es2015-arrow-functions@6.22.0
  | +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0
  | +-- babel-plugin-transform-es2015-block-scoping@6.23.0
  | +-- babel-plugin-transform-es2015-classes@6.23.0
  | | +-- babel-helper-define-map@6.23.0
  | | +-- babel-helper-function-name@6.23.0
  | | +-- babel-helper-optimise-call-expression@6.23.0
  | | `-- babel-helper-replace-supers@6.23.0
  | +-- babel-plugin-transform-es2015-computed-properties@6.22.0
  | +-- babel-plugin-transform-es2015-destructuring@6.23.0
  | +-- babel-plugin-transform-es2015-duplicate-keys@6.22.0
  | +-- babel-plugin-transform-es2015-for-of@6.23.0
  | +-- babel-plugin-transform-es2015-function-name@6.22.0
  | +-- babel-plugin-transform-es2015-literals@6.22.0
  | +-- babel-plugin-transform-es2015-modules-amd@6.24.0
  | +-- babel-plugin-transform-es2015-modules-commonjs@6.24.0
  | | `-- babel-plugin-transform-strict-mode@6.22.0
  | +-- babel-plugin-transform-es2015-modules-systemjs@6.23.0
  | | `-- babel-helper-hoist-variables@6.22.0
  | +-- babel-plugin-transform-es2015-modules-umd@6.24.0
  | +-- babel-plugin-transform-es2015-object-super@6.22.0
  | +-- babel-plugin-transform-es2015-parameters@6.23.0
  | | +-- babel-helper-call-delegate@6.22.0
  | | `-- babel-helper-get-function-arity@6.22.0
  | +-- babel-plugin-transform-es2015-shorthand-properties@6.22.0
  | +-- babel-plugin-transform-es2015-spread@6.22.0
  | +-- babel-plugin-transform-es2015-sticky-regex@6.22.0
  | | `-- babel-helper-regex@6.22.0
  | +-- babel-plugin-transform-es2015-template-literals@6.22.0
  | +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0
  | +-- babel-plugin-transform-es2015-unicode-regex@6.22.0
  | | `-- regexpu-core@2.0.0
  | |   +-- regenerate@1.3.2
  | |   +-- regjsgen@0.2.0
  | |   `-- regjsparser@0.1.5
  | |     `-- jsesc@0.5.0
  | `-- babel-plugin-transform-regenerator@6.22.0
  |   `-- regenerator-transform@0.9.8
  +-- colors@1.1.2
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- fibers@1.0.15
  +-- source-map-support@0.4.0  (git+https://github.com/Sage/node-source-map-support.git#ca4cf25ab660a84cbf489c73572f6451eafddc6e)
  | `-- source-map@0.1.32
  |   `-- amdefine@1.0.1
  +-- streamline-runtime@1.0.38
  | `-- regenerator-runtime@0.10.3
  `-- typescript@2.2.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/michael/nodetmp/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
$ node
> require("streamline").register({})
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at coffeeExecuting (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:30:24)
    at registerCoffee (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:74:28)
    at Object.exports.register (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:105:4)
    at repl:1:-39
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at coffeeExecuting (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:30:24)
    at registerCoffee (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:74:28)
    at Object.exports.register (/Users/michael/git/node/session/node_modules/streamline/lib/register.js:105:4)
    at repl:1:-39
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
^D
$
```

Then I create a file test.js containing the following:
```
console.log("debug1")
require("streamline").register({})
console.log("debug2")
```

And I run this code:

```
$ node test.js
debug1
debug2
$
```

What's going on here?  I'm actually running into this issue when I try to debug another issue with streamlined code and this is stopping me because I can't even start streamlining from the command line.

The other issue is in certain contexts when I try to require my streamlined module, I get the following error:
```
> var session = require("session")
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at coffeeExecuting (/Users/michael/node/node_modules/streamline/lib/register.js:30:24)
    at registerCoffee (/Users/michael/node/node_modules/streamline/lib/register.js:74:28)
    at Object.exports.register (/Users/michael/node/node_modules/streamline/lib/register.js:105:4)
    at Object.<anonymous> (/Users/michael/node/node_modules/session/index.js:1:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at coffeeExecuting (/Users/michael/node/node_modules/streamline/lib/register.js:30:24)
    at registerCoffee (/Users/michael/node/node_modules/streamline/lib/register.js:74:28)
    at Object.exports.register (/Users/michael/node/node_modules/streamline/lib/register.js:105:4)
    at Object.<anonymous> (/Users/michael/node/node_modules/session/index.js:1:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```

The error occurring at /Users/michael/node/node_modules/session/index.js:1 is the same code that is erroring above when *not* run from a script, namely:
```
require("streamline").register({})
```

**Comment by michael-ts** [comment]
Incidentally, if I put the above code ("var session = require("session")") into another .js file and run it directly, *that* works too.

**Comment by michael-ts** [comment]
If I comment out streamline/lib/register.js:105, which is calling registerCoffee, (I am using Javascript, not CoffeeScript) the error goes away.

**Comment by michael-ts** [comment]
Ok, I see what is happening... line 30 is assuming that process.argv[1] is a valid string.    Not sure why this assumption is made for registering coffeescript but not javascript.

**Comment by michael-ts** [comment]
I guess this is a bit of a red herring... if I'm calling streamlined code interactively, I need to use _node, not node!

**Comment by bjouhier** [comment]
I'm only catching up now. Your conclusion is right: you should be using `_node`. This way you don't have to call `register` and you can use the `_` parameter.
