### ISSUE TITLE
exceptions in streamlined code using express give no indication of where the problem is

### ISSUE THREAD

**Issue by michael-ts** [Sage/streamlinejs#362]
I'm using express-streamline, I've got a problem somewhere in my route handler.  When the route handler is run, the following message goes to both the console and to the browser that requested the page:

```
    <<< yield stack >>>
    <<< raw stack >>>
Error
    at stackTrace (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:211:49)
    at TypeError.get (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:190:11)
    at EventEmitter.logerror (/home/michael/node_modules/express/lib/application.js:630:52)
    at Object.immediate._onImmediate (timers.js:348:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

```

The actual file that caused the error, the offending line of code, isn't even in the stack trace!   The stack trace also doesn't even mention express-streamline, so I can't pin it there.

I also note that if I try to catch the exception myself in my code, I still can't figure out from the exception where the problem was, and I *still* get the original error message, even though I have already caught the error!

```
Trace: [TypeError: Cannot call method 'toLowerCase' of undefined]
    at _$$failure$$$ (/home/michael/node_modules/test/failure._js:29:14)
    at tryCatch (/home/michael/node_modules/streamline-runtime/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/michael/node_modules/streamline-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/michael/node_modules/streamline-runtime/node_modules/regenerator-runtime/runtime.js:116:21)
    at Object.glob.resume (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:57:40)
    at run (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:110:8)
    at F (eval at makeUnstarror (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:172:115), <anonymous>:13:7)
    at /home/michael/node_modules/express-streamline/index.js:89:32
    at Layer.handle [as handle_request] (/home/michael/node_modules/express-modular-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/michael/node_modules/express-modular-server/node_modules/express/lib/router/route.js:137:13)
    <<< yield stack >>>
    <<< raw stack >>>
Error
    at stackTrace (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:211:49)
    at TypeError.get (/home/michael/node_modules/streamline-runtime/lib/callbacks/runtime.js:190:11)
    at EventEmitter.logerror (/home/michael/node_modules/express/lib/application.js:630:52)
    at Object.immediate._onImmediate (timers.js:348:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

I don't know if this is a bug in streamline, an incompatibility with express, really a bug in express-streamline (which if so I can re-submit this there, but unfortunately I hold little hope for that route, as it seems express-streamline is no longer maintained, leaving basically no support for streamline for newer versions of express!!!)  or if I just don't understand how to deal with exceptions in streamline.  However, it is making it extremely difficult to debug streamlined code.

**Comment by bjouhier** [comment]
`express` is a callback based library and this problem is inherent to all callback based libraries: you don't get meaningful stack traces; all you get is a stacktrace of the last event dispatched from the event loop. Usually there is very little context in these stacktraces.

Streamline, on the other hand, gives you rich stacktraces that capture the _logical_ nesting of calls, even if the actual execution got broken into smaller events.

If the exception occurred inside the code that you wrote with streamline, you should get a meaningful stacktrace, at least up to the point where your streamlined code interfaces with express.

But if the exception did not occur in the scope of a streamlined try/catch you will only get the raw exception.

From your report it looks like the exception originated from line 29 of `failure._js`. Can you post the source code for this function (and the test function that calls it).

Also, stacktraces are better in _fibers_ mode than in _callbacks_ mode. Can you try forcing fibers mode (with `_node --runtime fibers`).

**Comment by michael-ts** [comment]
Yes, I can at least see where the exception occurred in my code *if I catch the exception myself*.

I've already tracked down and fixed this particular bug by adding extra debugging info, as well as wrapping the suspect code section in an explicit try/catch as indicated above. I don't recall exactly where the issue was now, line 29 isn't what it was when the bug occured but I do recall it was in some other module that I was calling from my streamlined code (failed._js) which was being called by express-streamline (it was a function exposed as an express route for a GET request).   So while it seems like that should qualify as "code I wrote with streamline" I don't get a meaningful stack trace if I'm not catching the error.

One other interesting thing I discovered though, is that if I add an additional function call in the call stack (e.g. if the initial function called by the router calls another function to do part of its work, and the exception happens in the second function) then I can actually see the first function in the call stack, but not the second.  If I get time today I'll try to rig up a simplified repro to illustrate.
