### ISSUE TITLE
Is the javascript spread operator supported with the latest version of streamline?

### ISSUE THREAD

**Issue by nuttamsingh** [Sage/streamlinejs#394]
I'm on version 3.0.0 and on node 14, am trying to use the spread javascript operator to construct objects from other objects but this doesn't seem to work and i get the following error

```
SyntaxError: /home/osboxes/Projects/dnanexus/nucleus/apiserver/tasks/init_database_helper._js: Unexpected token (988:4)
  986 |   };
  987 |   const second_proj_hash = {
> 988 |     ...shardKey,
      |     ^
  989 |     _id: secondProjId._id,
  990 |     'class': 'project',
  991 |     name: 'test-project-2',
    at Parser.pp$5.raise (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/osboxes/Projects/dnanexus/nucleus/common/temp/node_modules/.pnpm/babylon@6.18.0/node_modules/babylon/lib/index.js:3381:19) {
  pos: 28291,
  loc: Position { line: 988, column: 4 },
  _babel: true,
  codeFrame: '\x1B[0m \x1B[90m 986 | \x1B[39m  }\x1B[33m;\x1B[39m\n' +
    ' \x1B[90m 987 | \x1B[39m  \x1B[36mconst\x1B[39m second_proj_hash \x1B[33m=\x1B[39m {\n' +
    '\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 988 | \x1B[39m    \x1B[33m...\x1B[39mshardKey\x1B[33m,\x1B[39m\n' +
    ' \x1B[90m     | \x1B[39m    \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\n' +
    ' \x1B[90m 989 | \x1B[39m    _id\x1B[33m:\x1B[39m secondProjId\x1B[33m.\x1B[39m_id\x1B[33m,\x1B[39m\n' +
    " \x1B[90m 990 | \x1B[39m    \x1B[32m'class'\x1B[39m\x1B[33m:\x1B[39m \x1B[32m'project'\x1B[39m\x1B[33m,\x1B[39m\n" +
    " \x1B[90m 991 | \x1B[39m    name\x1B[33m:\x1B[39m \x1B[32m'test-project-2'\x1B[39m\x1B[33m,\x1B[39m\x1B[0m"
}
```

Am i missing something? Thanks!

**Comment by nuttamsingh** [comment]
https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread solves this
